name: focus
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter=1.1.1
  - ipykernel=6.29.5
  - nb_conda_kernels=2.5.1
  - pip
  - pip:
    - numpy==2.0.1
    - pandas=2.2.2
    - spe2py=2.0.0
    - matplotlib=3.9.2
    - scipy=1.14.1
    - seaborn=0.13.2
